default:
  # --- Django ---
  # https://docs.djangoproject.com/en/4.0/ref/settings/
  DEBUG: false
  ROOT_URLCONF: example.urls
  WSGI_APPLICATION: example.wsgi.application
  ALLOWED_HOSTS:
    - '*'
  INTERNAL_IPS:
    - '127.0.0.1'
    - 'localhost'
  INSTALLED_APPS:
    # 官方
    - django.contrib.contenttypes
    - django.contrib.staticfiles
    # 第三方
    - rest_framework
    - corsheaders  # CORS策略
  MIDDLEWARE:
    # https://docs.djangoproject.com/en/4.0/ref/middleware/#middleware-ordering
    - django.middleware.security.SecurityMiddleware
    - django.middleware.cache.UpdateCacheMiddleware
    # https://pypi.org/project/django-cors-headers/
    - corsheaders.middleware.CorsMiddleware
    - django.middleware.common.CommonMiddleware
    - django.middleware.csrf.CsrfViewMiddleware
    - django.middleware.cache.FetchFromCacheMiddleware
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql
      HOST:
      PORT: 5432
      USER:
      PASSWORD:
      NAME: example
  CACHES:
    default:
      BACKEND: django.core.cache.backends.db.DatabaseCache
      LOCATION: django_cache
  AUTH_USER_MODEL:
  TEMPLATES:
    - BACKEND: django.template.backends.django.DjangoTemplates
      APP_DIRS: True
  # Static files (CSS, JavaScript, Images)
  # https://docs.djangoproject.com/en/4.0/howto/static-files/
  STATIC_URL: /static/
  LANGUAGE_CODE: zh-Hans
  USE_I18N: true
  USE_L10N: true
  USE_TZ: false
  TIME_ZONE: Asia/Shanghai
  DEFAULT_AUTO_FIELD: django.db.models.BigAutoField

  # --- REST Framework ---
  # https://www.django-rest-framework.org/api-guide/settings/
  REST_FRAMEWORK:
    DEFAULT_AUTHENTICATION_CLASSES:
      # TODO: 引入drf-remote-auth的Authentication class
      - rest_framework.authentication.TokenAuthentication
    DEFAULT_PERMISSION_CLASSES:
      - rest_framework.permissions.AllowAny
    DEFAULT_RENDERER_CLASSES:
      - rest_framework.renderers.JSONRenderer
      - rest_framework.renderers.BrowsableAPIRenderer
      - rest_framework.renderers.AdminRenderer
    DEFAULT_PARSER_CLASSES:
      - rest_framework.parsers.JSONParser
    UNAUTHENTICATED_USER:
    TEST_REQUEST_DEFAULT_FORMAT: json
    TEST_REQUEST_RENDERER_CLASSES:
      - rest_framework.renderers.JSONRenderer

  # --- Django CORS ---
  CORS_ALLOW_ALL_ORIGINS: True

# ----- 开发环境 -----
development:
  DEBUG: true
  DATABASES:
    default:
      ENGINE: django.db.backends.sqlite3
      NAME: db.sqlite3
  CACHE_MIDDLEWARE_SECONDS: 0  # 关闭pre-view缓存
  # OpenAPI文档路径
  # OPENAPI_DOC_PATH: api/_build/openapi.yml

# ----- 测试环境 -----
testing:
  CACHE_MIDDLEWARE_SECONDS: 0  # 关闭pre-view缓存

# ----- 生产环境 -----
production:
  CACHE_MIDDLEWARE_SECONDS: 600  # pre-view缓存时长为10分钟