version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python3 manage.py migrate && python3 manage.py createcachetable && gunicorn {{ project_name }}.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: