"""
Django settings for {{ cookiecutter.project_name }} project.

Generated by `cookiecutter`, see
https://cookiecutter.readthedocs.io/en/stable/index.html

Supported by Django extension of `dynaconf`, see
https://www.dynaconf.com/django/
"""
import dynaconf

settings = dynaconf.DjangoDynaconf(__name__)
