"""
Django settings for {{ project_name }} project.

Generated by 'django-admin startproject' using Django {{ django_version }}.

For more information on this file, see
https://docs.djangoproject.com/en/{{ doc_version }}/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/{{ doc_version }}/ref/settings/

Supported by Django extension of [Dynaconf](https://www.dynaconf.com/django/).
"""
import dynaconf

settings = dynaconf.DjangoDynaconf(__name__)
